FROM supabase/gotrue:v2.164.0

USER root
COPY volumes/auth/certs/HARICA-GEANT-TLS-R1.crt /usr/local/share/ca-certificates/
COPY volumes/auth/certs/HARICA-TLS-Root-2021-RSA.crt /usr/local/share/ca-certificates/
RUN update-ca-certificates

USER supabase
