services:
  # MongoDB Service used internally
  mongo:
    image: mongo:7.0
    command: 
      - --replSet
      - rs0
      - --bind_ip_all
      - --quiet
      - --wiredTigerCacheSizeGB
      - "3"
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - mongo_storage:/data/db
    networks:
      - default
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    
    deploy:
      resources:
        limits:
          memory: 4G  # Limit to 4GB instead of consuming 8GB+
          cpus: '2.0'  # Limit to 2 CPU cores
        reservations:
          memory: 2G
          cpus: '1.0'

  # Initializes the MongoDB replica set. This service will not usually be actively running
  mongo-rs-init:
    image: mongo:7.0
    depends_on:
      mongo:
        condition: service_healthy  # Wait for mongo to be healthy
    restart: on-failure
    entrypoint:
      - bash
      - -c
      - 'mongosh --host mongo:27017 --eval ''try{rs.status().ok && quit(0)} catch {} rs.initiate({_id: "rs0", version: 1, members: [{ _id: 0, host : "mongo:27017" }]})'''
    networks:
      - default

volumes:
  mongo_storage:
