# yaml-language-server: $schema=../../../schema/schema.json

# See https://docs.powersync.com/self-hosting/telemetry
telemetry:
  # Opt out of reporting anonymized usage metrics to PowerSync telemetry service
  disable_telemetry_sharing: false

# Settings for source database replication
replication:
  connections:
    - type: postgresql
      uri: !env PS_DATA_SOURCE_URI

      # SSL settings
      sslmode: disable # 'verify-full' (default) or 'verify-ca' or 'disable'

# Connection settings for sync bucket storage
storage:
  type: mongodb
  uri: !env PS_MONGO_URI

# The port which the PowerSync API server will listen on
port: !env PS_PORT

# Specify sync rules
sync_rules:
  path: sync_rules.yaml

# Client (application end user) authentication settings
client_auth:
  # Enable this if using Supabase Auth
  supabase: true
  supabase_jwt_secret: !env PS_SUPABASE_JWT_SECRET
  #jwt_secret: !env PS_JWT_SECRET

  #allow_local_jwks: true

  # JWKS URIs can be specified here
  #jwks_uri: !env PS_JWKS_URL

  # Optional static collection of public keys for JWT verification
  #jwks:
  #  keys:
  #    - kty: RSA
  #      n: tRaRRWgrHY8ackZUlsdyMOx-Nw2LuO_wMHpiWZQtIKsOHl1hSA6tSRZnIY4jOqaulGmx6YXfGvNr8G034tNQ9jgs9_I2i5veHnzMj80p28OxUSz4A6DnUHuYswHJr6U75qG9MjRW6yWe_2sfu_UAUmMj-p6z44EuvwnaeLQ2ayYKuatGwY3GwyeQFnUAAo52uYDl8rLPnO4C6JbW09Er-lfmpMdTR60gEjD2Ex6AmYeKh5RXhFsyq5PPIgFMR16Z9lvjWD69X5XPRGFlhcsk2dOCPXcNP9lfM3xy_AkA9PLV_7u1B54cOTbJrz35EfGQJ3P5F-hYTU8kqfx0oRdsEQ
  #      e: AQAB
  #      alg: RS256
  #      kid: powersync-203d552549

  # JWKS audience
  audience: ["powersync-dev", "powersync"]

#api:
#  tokens:
#    # These tokens are used for local admin API route authentication
#    - use_a_better_token_in_production
