create table "public"."comanies" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null
);


alter table "public"."comanies" enable row level security;

CREATE UNIQUE INDEX comanies_pkey ON public.comanies USING btree (id);

alter table "public"."comanies" add constraint "comanies_pkey" PRIMARY KEY using index "comanies_pkey";

grant delete on table "public"."comanies" to "anon";

grant insert on table "public"."comanies" to "anon";

grant references on table "public"."comanies" to "anon";

grant select on table "public"."comanies" to "anon";

grant trigger on table "public"."comanies" to "anon";

grant truncate on table "public"."comanies" to "anon";

grant update on table "public"."comanies" to "anon";

grant delete on table "public"."comanies" to "authenticated";

grant insert on table "public"."comanies" to "authenticated";

grant references on table "public"."comanies" to "authenticated";

grant select on table "public"."comanies" to "authenticated";

grant trigger on table "public"."comanies" to "authenticated";

grant truncate on table "public"."comanies" to "authenticated";

grant update on table "public"."comanies" to "authenticated";

grant delete on table "public"."comanies" to "service_role";

grant insert on table "public"."comanies" to "service_role";

grant references on table "public"."comanies" to "service_role";

grant select on table "public"."comanies" to "service_role";

grant trigger on table "public"."comanies" to "service_role";

grant truncate on table "public"."comanies" to "service_role";

grant update on table "public"."comanies" to "service_role";


