COMMENT ON COLUMN inventory_archive.cluster.intkey IS 'Interner Key. Wird generiert.';
COMMENT ON COLUMN inventory_archive.cluster.cluster_name IS 'Traktnummer';
COMMENT ON COLUMN inventory_archive.cluster.state_responsible IS 'Kennung für das Aufnahme-Bundesland. Wird generiert..';
COMMENT ON COLUMN inventory_archive.cluster.topo_map_sheet IS 'Nummer der topgraphischen Karte 1:25.000';
COMMENT ON COLUMN inventory_archive.cluster.states_affected IS 'Liste der betroffenen Länder (Kürzel)';
COMMENT ON COLUMN inventory_archive.cluster.grid_density IS 'Zugehörigkeit zum Rasternetz';
COMMENT ON COLUMN inventory_archive.cluster.cluster_situation IS 'Traktstatus lt. Vorklärung + Feldaufnahme';
COMMENT ON COLUMN inventory_archive.plot_coordinates.center_location IS 'Soll-Ost-Koordinate WGS84 [Grad] für Traktecke, auch Longitude oder Längengrad genannt; EPSG: 4326';
COMMENT ON COLUMN inventory_archive.plot.intkey IS 'Interner Key. Wird generiert.';
COMMENT ON COLUMN inventory_archive.tree.intkey IS 'Interner Key. Wird generiert.';
COMMENT ON COLUMN inventory_archive.tree.tree_number IS 'Baumnummer BWI4';
COMMENT ON COLUMN inventory_archive.tree.tree_marked IS 'Permanente Trakteckenmarkierung gefunden/gesetzt';
COMMENT ON COLUMN inventory_archive.tree.tree_status IS 'Probebaumkennziffer BWI4';
COMMENT ON COLUMN inventory_archive.tree.azimuth IS 'Azimut [gon]';
COMMENT ON COLUMN inventory_archive.tree.distance IS 'Horizontalentfernung [cm]';
COMMENT ON COLUMN inventory_archive.tree.tree_species IS 'Baumart';
COMMENT ON COLUMN inventory_archive.tree.dbh IS 'gemessener BHD [mm]';
COMMENT ON COLUMN inventory_archive.tree.dbh_height IS 'Messhöhe des BHD [cm] bei Vorgängerinventur';
COMMENT ON COLUMN inventory_archive.tree.tree_height IS 'gemessene Baumhöhe [dm]';
COMMENT ON COLUMN inventory_archive.tree.stem_height IS 'gemessene Stammhöhe [dm]; nicht in allen Ländern';
COMMENT ON COLUMN inventory_archive.tree.tree_height_azimuth IS 'Azimut [Gon] der Messposition zum Höhenmessbaum; nicht in allen Ländern';
COMMENT ON COLUMN inventory_archive.tree.tree_height_distance IS 'Horizontalentfernung [cm] der Messposition zum Höhenmessbaum; nicht in allen Ländern';
COMMENT ON COLUMN inventory_archive.tree.tree_age IS 'Alter des Baumes [Jahre] zum Stichtag der Inventur 1.10.2022';
COMMENT ON COLUMN inventory_archive.tree.stem_breakage IS 'Höhenkennziffer';
COMMENT ON COLUMN inventory_archive.tree.stem_form IS 'Stammkennziffer';
COMMENT ON COLUMN inventory_archive.tree.pruning IS 'Astung';
COMMENT ON COLUMN inventory_archive.tree.within_stand IS 'Bestandeszugehörigkeit (0=nein, 1=ja)';
COMMENT ON COLUMN inventory_archive.tree.stand_layer IS 'Bestandesschicht';
COMMENT ON COLUMN inventory_archive.tree.damage_dead IS 'Totholzstücken ab 10 cm Dicke im Probekreis r=5,00 m vorhanden? (0=nein, 1/leer=ja)';
COMMENT ON COLUMN inventory_archive.tree.damage_peel_new IS 'jüngere/frische Schälschäden (0=nein, 1=ja)';
COMMENT ON COLUMN inventory_archive.tree.damage_peel_old IS 'ältere Schälschäden (0=nein, 1=ja)';
COMMENT ON COLUMN inventory_archive.tree.damage_logging IS 'Rücke- und Fällschäden (0=nein, 1=ja)';
COMMENT ON COLUMN inventory_archive.tree.damage_fungus IS 'Pilzkonsolen';
COMMENT ON COLUMN inventory_archive.tree.damage_resin IS 'Harzlachten (0=nein, 1=ja)';
COMMENT ON COLUMN inventory_archive.tree.damage_beetle IS 'Käferbohrlöcher (0=nein, 1=ja)';
COMMENT ON COLUMN inventory_archive.tree.damage_other IS 'sonstige Stammschäden (0=nein, 1=ja)';
COMMENT ON COLUMN inventory_archive.tree.cave_tree IS 'Biotop - Höhlenbaum (0=nein, 1=ja)';
COMMENT ON COLUMN inventory_archive.tree.crown_dead_wood IS 'Biotop - mehr als ein Drittel der Lichtkrone abgestorben oder drei starke Totäste   (0=nein, 1=ja)';
COMMENT ON COLUMN inventory_archive.tree.tree_top_drought IS 'Zopftrocknis (0=nein, 1=ja)';
COMMENT ON COLUMN inventory_archive.tree.bark_pocket IS 'mit sich lösender Rinde oder Rindentasche >500 cm². Mindestbereite 10 cm (0=nein, 1=ja)';
COMMENT ON COLUMN inventory_archive.tree.biotope_marked IS 'Biotop - Speziell markierter Biotopbaum';
COMMENT ON COLUMN inventory_archive.tree.bark_condition IS 'Erfassung des landesspezifischen WZP4-Merkmales WZ1 (Baum in Stichprobe)';
COMMENT ON COLUMN inventory_archive.deadwood.intkey IS 'Interner Key. Wird generiert.';
COMMENT ON COLUMN inventory_archive.deadwood.tree_species_group IS 'Baumartengruppe für Totholz';
COMMENT ON COLUMN inventory_archive.deadwood.dead_wood_type IS 'Totholztyp';
COMMENT ON COLUMN inventory_archive.deadwood.decomposition IS 'Zersetzungsgrad';
COMMENT ON COLUMN inventory_archive.deadwood.length_height IS 'Länge / Höhe Totholz [dm]';
COMMENT ON COLUMN inventory_archive.deadwood.diameter_butt IS 'Durchmesser am dicken Ende [cm] (liegende Bruchstücke); Schnittflächen- (Stöcke), Bhd (mit Wurzel, >=130 cm Länge)';
COMMENT ON COLUMN inventory_archive.deadwood.diameter_top IS 'Durchmesser am dünnen Ende [cm] (nur bei liegenden Totholz OHNE Wurzelanlauf)';
COMMENT ON COLUMN inventory_archive.deadwood.count IS 'Anzahl gleichartiger Bäume';
COMMENT ON COLUMN inventory_archive.deadwood.bark_pocket IS 'Rindentaschen > 500 cm² mit einer Mindestbreite von 10 cm (nur für stehendes Totholz)';
COMMENT ON COLUMN inventory_archive.position.intkey IS 'Interner Key. Wird generiert.';
COMMENT ON COLUMN inventory_archive.position.position_median IS 'GPS-WGS84-Messung Y (Latitude, Breitengrad, Nord), Median bei Vorgängerinventur';
COMMENT ON COLUMN inventory_archive.position.position_mean IS 'GPS-WGS84-Messung Y (Latitude, Breitengrad, Nord), Median bei Vorgängerinventur';
COMMENT ON COLUMN inventory_archive.position.hdop_mean IS 'horizontale Genauigkeit bei Vorgängerinventur (<4 gut, >8 schlecht)';
COMMENT ON COLUMN inventory_archive.position.pdop_mean IS 'Positionsgenauigkeit (<3 gut, >8 schlecht)';
COMMENT ON COLUMN inventory_archive.position.satellites_count_mean IS 'Anzahl der Satelliten bei Vorgängerinventur';
COMMENT ON COLUMN inventory_archive.position.measurement_count IS 'Anzahl der Messungen bei Vorgängerinventur';
COMMENT ON COLUMN inventory_archive.position.rtcm_age IS 'RTCMAlter bei Vorgängerinventur';
COMMENT ON COLUMN inventory_archive.position.start_measurement IS 'UTC-Startzeit, Beginn der Messung [JJJJMMTT hh:mm:ss] bei Vorgängerinventur';
COMMENT ON COLUMN inventory_archive.position.stop_measurement IS 'UTC-Stopzeit, Ende der Messung [JJJJMMTT hh:mm:ss] bei Vorgängerinventur';
COMMENT ON COLUMN inventory_archive.position.device_gnss IS 'Gerät / Geräteklasse';
COMMENT ON COLUMN inventory_archive.position.quality IS 'Qualität der verwendeten GNSS-Einmessung bei Vorgängerinventur';
COMMENT ON COLUMN inventory_archive.edges.intkey IS 'Interner Key. Wird generiert.';
COMMENT ON COLUMN inventory_archive.edges.edge_status IS 'Kennziffer des Wald-/Bestandesrandes BWI4';
COMMENT ON COLUMN inventory_archive.edges.edge_number IS 'Waldrandnummer BWI4';
COMMENT ON COLUMN inventory_archive.edges.edge_type IS 'Art des Wald- /Bestandesrandes';
COMMENT ON COLUMN inventory_archive.edges.terrain IS 'Vorgelagertes Terrain';
COMMENT ON COLUMN inventory_archive.subplots_relative_position.azimuth IS 'Lage der Probekreise r=1 / 2 m (JUNG - Baumgrößen 0-6) bezüglich Traktecke';
COMMENT ON COLUMN inventory_archive.subplots_relative_position.distance IS 'Horizontalentfernung [cm] der Probekreise r=1 / 2 m (Baumgrößen 0-6)';
COMMENT ON COLUMN inventory_archive.subplots_relative_position.radius IS 'Radius [m] des Probekreises für Bäume der Baumgröße 0 {1 oder 2 m}';
COMMENT ON COLUMN inventory_archive.regeneration.intkey IS 'Interner Key. Wird generiert.';
COMMENT ON COLUMN inventory_archive.regeneration.tree_species IS 'Baumart';
COMMENT ON COLUMN inventory_archive.regeneration.tree_size_class IS 'Baumgrößenklasse';
COMMENT ON COLUMN inventory_archive.regeneration.damage_peel IS 'Schälschäden (frische und/oder ältere)';
COMMENT ON COLUMN inventory_archive.regeneration.protection_individual IS 'Einzelschutz der Bäume (0=nein, 1=ja)';
COMMENT ON COLUMN inventory_archive.regeneration.tree_count IS 'Anzahl gleichartiger Bäume';
COMMENT ON COLUMN inventory_archive.structure_lt4m.intkey IS 'Interner Key. Wird generiert.';
COMMENT ON COLUMN inventory_archive.structure_lt4m.tree_species IS 'Baumart';
COMMENT ON COLUMN inventory_archive.structure_lt4m.coverage IS 'Anteil der Baumart in Zehntel (Deckungsgrad entspricht 10 Zehntel = 100 %)';
COMMENT ON COLUMN inventory_archive.plot.plot_name IS 'Trakteckennummer (1=A, 2=B, 3=C, 4=D)';
COMMENT ON COLUMN inventory_archive.plot.cluster_name IS 'Traktnummer';
COMMENT ON COLUMN inventory_archive.plot.sampling_stratum IS 'Verdichtungsgebiet';
COMMENT ON COLUMN inventory_archive.plot.federal_state IS 'Kennung für das Aufnahme-Bundesland. Wird generiert..';
COMMENT ON COLUMN inventory_archive.plot.growth_district IS 'Wuchsbezirk';
COMMENT ON COLUMN inventory_archive.plot.forest_status IS 'Waldentscheid an der Traktecke lt. Vorklärung + Feldaufnahme';
COMMENT ON COLUMN inventory_archive.plot.accessibility IS 'Begehbarkeit der Traktecke lt. Vorklärung + Feldaufnahme';
COMMENT ON COLUMN inventory_archive.plot.forest_office IS 'Forstamt';
COMMENT ON COLUMN inventory_archive.plot.elevation_level IS 'Natürliche Höhenstufe';
COMMENT ON COLUMN inventory_archive.plot.property_type IS 'Eigentumsart';
COMMENT ON COLUMN inventory_archive.plot.property_size_class IS 'Eigentumsgrößenklasse';
COMMENT ON COLUMN inventory_archive.plot.forest_community IS 'potentielle natürliche Waldgesellschaft lt. Vorklärung';
COMMENT ON COLUMN inventory_archive.plot.ffh_forest_type IS 'WLT - Waldlebensraumtyp lt. Vorklärung';
COMMENT ON COLUMN inventory_archive.plot.ffh_forest_type_field IS 'Waldlebensraumtyp lt. Feldaufnahme';
COMMENT ON COLUMN inventory_archive.plot.land_use IS 'Landnutzungsart';
COMMENT ON COLUMN inventory_archive.plot.coast IS 'bewaldete Küstendüne (unmittelbar in Küsten- bzw. Strandnähe)';
COMMENT ON COLUMN inventory_archive.plot.sandy IS 'trockener sandiger Boden oder wechseltrockene Standorte oder Vegetationszeiger oder  andere gesicherte Bestätigung (j/n)';
COMMENT ON COLUMN inventory_archive.plot.protected_landscape IS 'Landschaftschutzgebiet';
COMMENT ON COLUMN inventory_archive.plot.long_time_forest IS 'Historischer Wald, seit langem (bisher nur NI) Input für WLT_Algorithmus';
COMMENT ON COLUMN inventory_archive.plot.harvest_restriction IS 'Nutzungseinschränkung';
COMMENT ON COLUMN inventory_archive.plot.harvest_restriction_nature_reserve IS 'Ursache der Nutzungseinschränkung 1-Naturschutz (1=ja, 0=nein)';
COMMENT ON COLUMN inventory_archive.plot.harvest_restriction_protection_forest IS 'Ursache der Nutzungseinschränkung 2-Schutzwald (1=ja, 0=nein)';
COMMENT ON COLUMN inventory_archive.plot.harvest_restriction_recreational_forest IS 'Ursache der Nutzungseinschränkung 3-Erholungswald (1=ja, 0=nein)';
COMMENT ON COLUMN inventory_archive.plot.harvest_restriction_scattered IS 'Ursache der Nutzungseinschränkung 11-Splitterbesitz mit unwirtschaftlicher Größe (1=ja, 0=nein)';
COMMENT ON COLUMN inventory_archive.plot.harvest_restriction_fragmented IS 'Ursache der Nutzungseinschränkung 12-Streulage (1=ja, 0=nein)';
COMMENT ON COLUMN inventory_archive.plot.harvest_restriction_insufficient_access IS 'Ursache der Nutzungseinschränkung 13-unzureichender Erschließung (1=ja, 0=nein)';
COMMENT ON COLUMN inventory_archive.plot.harvest_restriction_wetness IS 'Ursache der Nutzungseinschränkung 14-Geländeeigenschaften, Nassstandort (1=ja, 0=nein)';
COMMENT ON COLUMN inventory_archive.plot.harvest_restriction_low_yield IS 'Ursache der Nutzungseinschränkung 15-geringer Ertragserwartungen (dGZ < 1 m³/(ha*a)) (1=ja, 0=nein)';
COMMENT ON COLUMN inventory_archive.plot.harvest_restriction_private_conservation IS 'Ursache der Nutzungseinschränkung 16-Schutzflächen in Eigenbindung (z.B. Naturreservate) (1=ja, 0=nein)';
COMMENT ON COLUMN inventory_archive.plot.harvest_restriction_other_internalcause IS 'Ursache der Nutzungseinschränkung 19-sonstige innerbetriebliche Ursachen (1=ja, 0=nein)';
COMMENT ON COLUMN inventory_archive.plot.marker_status IS 'Permanente Trakteckenmarkierung gefunden/gesetzt';
--COMMENT ON COLUMN inventory_archive.plot.marker_azimuth IS 'Position (Azimut [gon]) der permanenten Trakteckenmarkierung';
--COMMENT ON COLUMN inventory_archive.plot.marker_distance IS 'Position (Horizontalentfernung [cm]) der permanenten Trakteckenmarkierung';
COMMENT ON COLUMN inventory_archive.plot.municipality IS 'Amtlicher Gemeindeschlüssel (8-stellig, Pos 1+2=Bl, 3=RegBez, 4-5=Kreis, 6-7=Gemeinde)';
--COMMENT ON COLUMN inventory_archive.plot.usage_type IS 'Nutzungsart';
COMMENT ON COLUMN inventory_archive.plot.marker_profile IS 'Profil der permanenten Trakteckenmarkierung; fakultativ';
COMMENT ON COLUMN inventory_archive.plot.terrain_form IS 'Geländeform';
COMMENT ON COLUMN inventory_archive.plot.terrain_slope IS 'Geländeneigung [Grad]';
COMMENT ON COLUMN inventory_archive.plot.terrain_exposure IS 'Geländeexposition [Gon]';
COMMENT ON COLUMN inventory_archive.plot.management_type IS 'Betriebsart';
COMMENT ON COLUMN inventory_archive.plot.harvest_condition IS 'Bedingungen für die Holzernte';
COMMENT ON COLUMN inventory_archive.plot.biotope IS 'Geschütztes Waldbiotop bei Vorgängerinventur (BWI 2011-2014)';
COMMENT ON COLUMN inventory_archive.plot.stand_development_phase IS 'Entwicklungsphase / Wuchsklasse / Dimensionsklasse';
COMMENT ON COLUMN inventory_archive.plot.stand_layer_regeneration IS 'Bestandesschicht aller jungen Bäume der Probekreise r=1 / 2m (Baumgrößen 0-6)';
COMMENT ON COLUMN inventory_archive.plot.fence_regeneration IS 'Zäunung der Probeflächen r=1 / 2 m (Baumgrößen 0-6)';
COMMENT ON COLUMN inventory_archive.plot.trees_greater_4meter_mirrored IS 'Art der Spiegelung aller Bäume der Bestockung über 4 m Höhe';
COMMENT ON COLUMN inventory_archive.plot.trees_greater_4meter_basal_area_factor IS 'Zählfaktor aller Bäume der Bestockung über 4 m Höhe';
COMMENT ON COLUMN inventory_archive.plot.trees_less_4meter_layer IS 'Schicht';
COMMENT ON COLUMN inventory_archive.plot.biogeographische_region IS 'Biogeographische Region';
COMMENT ON COLUMN inventory_archive.plot.biosphaere IS 'Biosphärenreservat';
COMMENT ON COLUMN inventory_archive.plot.ffh IS 'Flora-Fauna-Habitat-Gebiet';
COMMENT ON COLUMN inventory_archive.plot.national_park IS 'Nationalpark';
COMMENT ON COLUMN inventory_archive.plot.natur_park IS 'Naturpark';
COMMENT ON COLUMN inventory_archive.plot.vogel_schutzgebiet IS 'Vogelschutzgebiet';
COMMENT ON COLUMN inventory_archive.plot.natur_schutzgebiet IS 'Naturschutzgebiet';
COMMENT ON COLUMN inventory_archive.plot_support_points.azimuth IS 'Azimut in [gon]';
COMMENT ON COLUMN inventory_archive.plot_support_points.distance IS 'Horizontalentfernung [cm]';
COMMENT ON COLUMN inventory_archive.plot_support_points.point_type IS 'Art/Zweck der gesetzten Markierung';
COMMENT ON COLUMN inventory_archive.plot_support_points.is_marked IS 'Wurde der Punkt mit einem Eisen gesichert?';
COMMENT ON COLUMN inventory_archive.plot_support_points.note IS 'Freitext-Kommentar';
COMMENT ON COLUMN inventory_archive.cluster_move.rotation IS 'Trakt ist insgesamt gegenüber Soll-Koordinaten verdreht, Dreh-Azimut [gon] von Soll zu Ist';
COMMENT ON COLUMN inventory_archive.cluster_move.azimuth IS 'Trakt ist insgesamt gegenüber Soll-Koordinaten verschoben, Azimut [gon] der Abweichung von Soll zu ist';
COMMENT ON COLUMN inventory_archive.cluster_move.distance IS 'Trakt ist insgesamt gegenüber Soll-Koordinaten verschoben, Horizontalentfernung [m] der Abweichung';