-- ==========================================================================
-- MIGRATION: Stop service/admin writes from nulling records.updated_by
-- ==========================================================================
-- Problem (root cause of the "multiple record_changes per second"):
--   updated_by IS DISTINCT FROM in the on_record_updated trigger is kept on
--   purpose -- the History must keep showing WHO edited a record. The noise
--   does not come from that trigger, it comes from updated_by being flipped
--   back and forth:
--
--     * App writes (role authenticated) -> handle_updated_by sets
--       updated_by = auth.uid()  = the user.
--     * Admin / service_role / SQL-editor writes (role postgres/supabase_admin)
--       have auth.uid() = NULL, so handle_updated_by OVERWRITES updated_by with
--       NULL, wiping the last real editor.
--
--   Every hand-off between those two therefore flips updated_by (user <-> NULL)
--   and, because the app also pushes very frequent local_updated_at writes,
--   on_record_updated mints a fresh history version with no real content change.
--   Evidence: ~40% of all record_changes rows (116k / 292k) were generated by an
--   updated_by change alone.
--
-- Fix:
--   updated_by must only ever hold a real end-user id. Service-role / admin /
--   SQL-editor writes (auth.uid() IS NULL) must LEAVE updated_by untouched
--   instead of nulling it. That removes the user<->NULL flip at the source while
--   keeping updated_by in the on_record_updated trigger (genuine user A -> user B
--   editor changes are still recorded). No trigger definition is changed here.
--
--   The existing app.skip_updated_by opt-out (20260603000000) is preserved; note
--   the live DB had drifted back to the plain auth.uid() version, so this also
--   re-establishes that flag.
-- ==========================================================================

CREATE OR REPLACE FUNCTION public.update_updated_by_column() RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  -- Explicit opt-out for batch jobs: SET app.skip_updated_by = 'on'
  IF current_setting('app.skip_updated_by', true) = 'on' THEN
    RETURN NEW;
  END IF;

  -- Only stamp updated_by when a real end-user is authenticated.
  -- Non-user writes (auth.uid() IS NULL: service_role, postgres, SQL editor,
  -- batch admin UPDATEs) must NOT clobber the last real editor -- doing so is
  -- what produced the spurious updated_by NULL<->user history churn.
  IF auth.uid() IS NOT NULL THEN
    NEW.updated_by = auth.uid();
  END IF;

  RETURN NEW;
END;
$$;
